### ISSUE TITLE
Does PLM make only read-only queries, or does it also write?

### ISSUE THREAD

**Issue by ralphbean** [release-engineering/product-listings-manager#43]
If it only reads, then we should configure it in prod to use the new hot standby database instead of the main one in the clustered setup.  It would be faster.

**Comment by ktdreyer** [comment]
That's correct, it's only reads. I didn't know we had a hot standby read-only DB :)

**Comment by ralphbean** [comment]
Ping Mr. Costa to learn more.  :)
